### ISSUE TITLE
Feature Request:  maxHeight

### ISSUE THREAD

**Issue by NfNitLoop** [maximousblk/chart#1]
I like letting graphs grow automatically depending on their data points, but I'd love to be able to put an upper bound on how big they can grow w/o having to handle that logic myself.

(Thanks for this tool! It's working great for me! 😄)

**Comment by NfNitLoop** [comment]
Oh! I think height operates like I want `maxHeight` to.  👍

I guess it might be worth updating docs to make that clear?

**Comment by NfNitLoop** [comment]
Aaand on further testing, it doesn't work like maxHeight. 😆 

I had a data set that was a flat line, and with `height: 8` it was just showing a single line. 

However, once I get two data points, (say, 1, and 2) it now fills out to `height + 1` lines, filling in unused fractional values between the two data points that actually exist.

**Comment by maximousblk** [comment]
this port is supposed to be a 1:1 port of the original https://github.com/kroitor/asciichart library. please open up a new issue in that repo for new features
